ALTER TABLE users ADD COLUMN avatar_image_key TEXT;
ALTER TABLE users ADD COLUMN avatar_preset TEXT;
ALTER TABLE users ADD COLUMN bio TEXT;
ALTER TABLE users ADD COLUMN gamer_dna TEXT NOT NULL DEFAULT '[]';
ALTER TABLE users ADD COLUMN discovery_zone TEXT;
ALTER TABLE users ADD COLUMN notify_events INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN notify_group_invites INTEGER NOT NULL DEFAULT 1;
